import { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://andamus.it";

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/it/",
          "/en/",
          "/de/",
          "/it/cerca",
          "/en/cerca",
          "/de/cerca",
          "/it/corsa/",
          "/en/corsa/",
          "/de/corsa/",
          "/it/u/",
          "/en/u/",
          "/de/u/",
          "/it/termini-e-condizioni",
          "/en/termini-e-condizioni",
          "/de/termini-e-condizioni",
          "/it/privacy-policy",
          "/en/privacy-policy",
          "/de/privacy-policy",
        ],
        disallow: [
          "/api/",
          "/it/admin/",
          "/en/admin/",
          "/de/admin/",
          "/it/profilo",
          "/en/profilo",
          "/de/profilo",
          "/it/chat/",
          "/en/chat/",
          "/de/chat/",
          "/it/offri",
          "/en/offri",
          "/de/offri",
          "/it/richieste",
          "/en/richieste",
          "/de/richieste",
          "/it/richiesta/",
          "/en/richiesta/",
          "/de/richiesta/",
          "/it/verifica",
          "/en/verifica",
          "/de/verifica",
          "/it/premium",
          "/en/premium",
          "/de/premium",
          "/it/statistiche",
          "/en/statistiche",
          "/de/statistiche",
          "/it/invita",
          "/en/invita",
          "/de/invita",
          "/it/gruppi",
          "/en/gruppi",
          "/de/gruppi",
          "/it/gruppo/",
          "/en/gruppo/",
          "/de/gruppo/",
          "/it/eventi",
          "/en/eventi",
          "/de/eventi",
          "/it/cancella",
          "/en/cancella",
          "/de/cancella",
          "/it/lansare",
          "/en/lansare",
          "/de/lansare",
          "/it/join",
          "/en/join",
          "/de/join",
          "/it/auth/",
          "/en/auth/",
          "/de/auth/",
          "/coming-soon",
          "/offline",
          "/_next/",
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  };
}
