-- Sardinia Location System
-- All cities, villages, airports, ports, and universities

-- Enable pg_trgm for fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS locations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL, -- 'city', 'airport', 'port', 'university'
  province TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  population INTEGER DEFAULT 0,
  popular BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS locations_name_trgm_idx ON locations USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS locations_type_idx ON locations (type);
CREATE INDEX IF NOT EXISTS locations_popular_idx ON locations (popular);
CREATE INDEX IF NOT EXISTS locations_slug_idx ON locations (slug);

-- RLS
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Locations are viewable by everyone" ON locations FOR SELECT USING (true);

-- Function to search locations with fuzzy matching and grouping
CREATE OR REPLACE FUNCTION search_locations(search_query TEXT, max_results INTEGER DEFAULT 10)
RETURNS TABLE (
  id UUID,
  name TEXT,
  slug TEXT,
  type TEXT,
  province TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  population INTEGER,
  popular BOOLEAN,
  similarity REAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    l.id, l.name, l.slug, l.type, l.province, l.latitude, l.longitude, l.population, l.popular,
    similarity(l.name, search_query) as similarity
  FROM locations l
  WHERE 
    l.name ILIKE '%' || search_query || '%'
    OR similarity(l.name, search_query) > 0.3
  ORDER BY 
    l.popular DESC,
    similarity DESC,
    l.population DESC
  LIMIT max_results;
END;
$$ LANGUAGE plpgsql;
INSERT INTO locations (name, slug, type, province, latitude, longitude, population, popular) VALUES
('Abbasanta', 'abbasanta', 'city', '', NULL, NULL, 0, FALSE),
('Aggius', 'aggius', 'city', '', NULL, NULL, 0, FALSE),
('Aglientu', 'aglientu', 'city', '', NULL, NULL, 0, FALSE),
('Aidomaggiore', 'aidomaggiore', 'city', '', NULL, NULL, 0, FALSE),
('Albagiara', 'albagiara', 'city', '', NULL, NULL, 0, FALSE),
('Ales', 'ales', 'city', '', NULL, NULL, 0, FALSE),
('Alghero', 'alghero', 'city', 'SS', 40.558, 8.319, 43964, TRUE),
('Allai', 'allai', 'city', '', NULL, NULL, 0, FALSE),
('Alà dei Sardi', 'al-dei-sardi', 'city', '', NULL, NULL, 0, FALSE),
('Anela', 'anela', 'city', '', NULL, NULL, 0, FALSE),
('Arborea', 'arborea', 'city', '', NULL, NULL, 0, FALSE),
('Arbus', 'arbus', 'city', '', NULL, NULL, 0, FALSE),
('Ardara', 'ardara', 'city', '', NULL, NULL, 0, FALSE),
('Ardauli', 'ardauli', 'city', '', NULL, NULL, 0, FALSE),
('Aritzo', 'aritzo', 'city', '', NULL, NULL, 0, FALSE),
('Armungia', 'armungia', 'city', '', NULL, NULL, 0, FALSE),
('Arzachena', 'arzachena', 'city', 'SS', 41.0786, 9.3817, 13640, TRUE),
('Arzana', 'arzana', 'city', '', NULL, NULL, 0, FALSE),
('Assemini', 'assemini', 'city', 'CA', 39.29, 9.0067, 26767, TRUE),
('Assolo', 'assolo', 'city', '', NULL, NULL, 0, FALSE),
('Asuni', 'asuni', 'city', '', NULL, NULL, 0, FALSE),
('Atzara', 'atzara', 'city', '', NULL, NULL, 0, FALSE),
('Austis', 'austis', 'city', '', NULL, NULL, 0, FALSE),
('Badesi', 'badesi', 'city', '', NULL, NULL, 0, FALSE),
('Ballao', 'ballao', 'city', '', NULL, NULL, 0, FALSE),
('Banari', 'banari', 'city', '', NULL, NULL, 0, FALSE),
('Baradili', 'baradili', 'city', '', NULL, NULL, 0, FALSE),
('Baratili San Pietro', 'baratili-san-pietro', 'city', '', NULL, NULL, 0, FALSE),
('Baressa', 'baressa', 'city', '', NULL, NULL, 0, FALSE),
('Bari Sardo', 'bari-sardo', 'city', '', NULL, NULL, 0, FALSE),
('Barrali', 'barrali', 'city', '', NULL, NULL, 0, FALSE),
('Barumini', 'barumini', 'city', '', NULL, NULL, 0, FALSE),
('Bauladu', 'bauladu', 'city', '', NULL, NULL, 0, FALSE),
('Baunei', 'baunei', 'city', '', NULL, NULL, 0, FALSE),
('Belvì', 'belv', 'city', '', NULL, NULL, 0, FALSE),
('Benetutti', 'benetutti', 'city', '', NULL, NULL, 0, FALSE),
('Berchidda', 'berchidda', 'city', '', NULL, NULL, 0, FALSE),
('Bessude', 'bessude', 'city', '', NULL, NULL, 0, FALSE),
('Bidonì', 'bidon', 'city', '', NULL, NULL, 0, FALSE),
('Birori', 'birori', 'city', '', NULL, NULL, 0, FALSE),
('Bitti', 'bitti', 'city', '', NULL, NULL, 0, FALSE),
('Bolotana', 'bolotana', 'city', '', NULL, NULL, 0, FALSE),
('Bonarcado', 'bonarcado', 'city', '', NULL, NULL, 0, FALSE),
('Bonnanaro', 'bonnanaro', 'city', '', NULL, NULL, 0, FALSE),
('Bono', 'bono', 'city', '', NULL, NULL, 0, FALSE),
('Bonorva', 'bonorva', 'city', '', NULL, NULL, 0, FALSE),
('Boroneddu', 'boroneddu', 'city', '', NULL, NULL, 0, FALSE),
('Borore', 'borore', 'city', '', NULL, NULL, 0, FALSE),
('Bortigali', 'bortigali', 'city', '', NULL, NULL, 0, FALSE),
('Bortigiadas', 'bortigiadas', 'city', '', NULL, NULL, 0, FALSE),
('Borutta', 'borutta', 'city', '', NULL, NULL, 0, FALSE),
('Bosa', 'bosa', 'city', 'OR', 40.2983, 8.5011, 7927, FALSE),
('Bottidda', 'bottidda', 'city', '', NULL, NULL, 0, FALSE),
('Buddusò', 'buddus', 'city', '', NULL, NULL, 0, FALSE),
('Budoni', 'budoni', 'city', 'SS', 40.7025, 9.7078, 5312, TRUE),
('Buggerru', 'buggerru', 'city', '', NULL, NULL, 0, FALSE),
('Bultei', 'bultei', 'city', '', NULL, NULL, 0, FALSE),
('Bulzi', 'bulzi', 'city', '', NULL, NULL, 0, FALSE),
('Burcei', 'burcei', 'city', '', NULL, NULL, 0, FALSE),
('Burgos', 'burgos', 'city', '', NULL, NULL, 0, FALSE),
('Busachi', 'busachi', 'city', '', NULL, NULL, 0, FALSE),
('Cabras', 'cabras', 'city', '', NULL, NULL, 0, FALSE),
('Cagliari', 'cagliari', 'city', 'CA', 39.2238, 9.1217, 154083, TRUE),
('Calangianus', 'calangianus', 'city', '', NULL, NULL, 0, FALSE),
('Calasetta', 'calasetta', 'city', '', NULL, NULL, 0, FALSE),
('Capoterra', 'capoterra', 'city', 'CA', 39.1764, 8.9719, 23583, TRUE),
('Carbonia', 'carbonia', 'city', 'SU', 39.1672, 8.5222, 28265, TRUE),
('Cardedu', 'cardedu', 'city', '', NULL, NULL, 0, FALSE),
('Cargeghe', 'cargeghe', 'city', '', NULL, NULL, 0, FALSE),
('Carloforte', 'carloforte', 'city', 'SU', 39.145, 8.3058, 6194, TRUE),
('Castelsardo', 'castelsardo', 'city', 'SS', 40.9108, 8.716, 5990, TRUE),
('Castiadas', 'castiadas', 'city', '', NULL, NULL, 0, FALSE),
('Cheremule', 'cheremule', 'city', '', NULL, NULL, 0, FALSE),
('Chiaramonti', 'chiaramonti', 'city', '', NULL, NULL, 0, FALSE),
('Codrongianos', 'codrongianos', 'city', '', NULL, NULL, 0, FALSE),
('Collinas', 'collinas', 'city', '', NULL, NULL, 0, FALSE),
('Cossoine', 'cossoine', 'city', '', NULL, NULL, 0, FALSE),
('Cuglieri', 'cuglieri', 'city', '', NULL, NULL, 0, FALSE),
('Curcuris', 'curcuris', 'city', '', NULL, NULL, 0, FALSE),
('Decimomannu', 'decimomannu', 'city', '', NULL, NULL, 0, FALSE),
('Decimoputzu', 'decimoputzu', 'city', '', NULL, NULL, 0, FALSE),
('Desulo', 'desulo', 'city', '', NULL, NULL, 0, FALSE),
('Dolianova', 'dolianova', 'city', '', NULL, NULL, 0, FALSE),
('Domus de Maria', 'domus-de-maria', 'city', '', NULL, NULL, 0, FALSE),
('Domusnovas', 'domusnovas', 'city', '', NULL, NULL, 0, FALSE),
('Donori', 'donori', 'city', '', NULL, NULL, 0, FALSE),
('Dorgali', 'dorgali', 'city', '', NULL, NULL, 0, FALSE),
('Dualchi', 'dualchi', 'city', '', NULL, NULL, 0, FALSE),
('Elini', 'elini', 'city', '', NULL, NULL, 0, FALSE),
('Elmas', 'elmas', 'city', '', NULL, NULL, 0, FALSE),
('Erula', 'erula', 'city', '', NULL, NULL, 0, FALSE),
('Escalaplano', 'escalaplano', 'city', '', NULL, NULL, 0, FALSE),
('Escolca', 'escolca', 'city', '', NULL, NULL, 0, FALSE),
('Esporlatu', 'esporlatu', 'city', '', NULL, NULL, 0, FALSE),
('Esterzili', 'esterzili', 'city', '', NULL, NULL, 0, FALSE),
('Florinas', 'florinas', 'city', '', NULL, NULL, 0, FALSE),
('Fluminimaggiore', 'fluminimaggiore', 'city', '', NULL, NULL, 0, FALSE),
('Flussio', 'flussio', 'city', '', NULL, NULL, 0, FALSE),
('Fonni', 'fonni', 'city', '', NULL, NULL, 0, FALSE),
('Fordongianus', 'fordongianus', 'city', '', NULL, NULL, 0, FALSE),
('Furtei', 'furtei', 'city', '', NULL, NULL, 0, FALSE),
('Gadoni', 'gadoni', 'city', '', NULL, NULL, 0, FALSE),
('Gairo', 'gairo', 'city', '', NULL, NULL, 0, FALSE),
('Galtellì', 'galtell', 'city', '', NULL, NULL, 0, FALSE),
('Gavoi', 'gavoi', 'city', '', NULL, NULL, 0, FALSE),
('Genoni', 'genoni', 'city', '', NULL, NULL, 0, FALSE),
('Genuri', 'genuri', 'city', '', NULL, NULL, 0, FALSE),
('Gergei', 'gergei', 'city', '', NULL, NULL, 0, FALSE),
('Gesico', 'gesico', 'city', '', NULL, NULL, 0, FALSE),
('Gesturi', 'gesturi', 'city', '', NULL, NULL, 0, FALSE),
('Ghilarza', 'ghilarza', 'city', '', NULL, NULL, 0, FALSE),
('Giave', 'giave', 'city', '', NULL, NULL, 0, FALSE),
('Giba', 'giba', 'city', '', NULL, NULL, 0, FALSE),
('Girasole', 'girasole', 'city', '', NULL, NULL, 0, FALSE),
('Golfo Aranci', 'golfo-aranci', 'city', '', NULL, NULL, 0, FALSE),
('Goni', 'goni', 'city', '', NULL, NULL, 0, FALSE),
('Gonnesa', 'gonnesa', 'city', '', NULL, NULL, 0, FALSE),
('Gonnoscodina', 'gonnoscodina', 'city', '', NULL, NULL, 0, FALSE),
('Gonnosfanadiga', 'gonnosfanadiga', 'city', '', NULL, NULL, 0, FALSE),
('Gonnosnò', 'gonnosn', 'city', '', NULL, NULL, 0, FALSE),
('Gonnostramatza', 'gonnostramatza', 'city', '', NULL, NULL, 0, FALSE),
('Guamaggiore', 'guamaggiore', 'city', '', NULL, NULL, 0, FALSE),
('Guasila', 'guasila', 'city', '', NULL, NULL, 0, FALSE),
('Guspini', 'guspini', 'city', 'SU', 39.5408, 8.6339, 11846, FALSE),
('Iglesias', 'iglesias', 'city', 'SU', 39.3094, 8.537, 26784, TRUE),
('Ilbono', 'ilbono', 'city', '', NULL, NULL, 0, FALSE),
('Illorai', 'illorai', 'city', '', NULL, NULL, 0, FALSE),
('Irgoli', 'irgoli', 'city', '', NULL, NULL, 0, FALSE),
('Isili', 'isili', 'city', '', NULL, NULL, 0, FALSE),
('Ittireddu', 'ittireddu', 'city', '', NULL, NULL, 0, FALSE),
('Ittiri', 'ittiri', 'city', '', NULL, NULL, 0, FALSE),
('Jerzu', 'jerzu', 'city', '', NULL, NULL, 0, FALSE),
('La Maddalena', 'la-maddalena', 'city', 'SS', 41.2176, 9.4051, 11229, TRUE),
('Laconi', 'laconi', 'city', '', NULL, NULL, 0, FALSE),
('Laerru', 'laerru', 'city', '', NULL, NULL, 0, FALSE),
('Lanusei', 'lanusei', 'city', '', NULL, NULL, 0, FALSE),
('Las Plassas', 'las-plassas', 'city', '', NULL, NULL, 0, FALSE),
('Lei', 'lei', 'city', '', NULL, NULL, 0, FALSE),
('Loceri', 'loceri', 'city', '', NULL, NULL, 0, FALSE),
('Loculi', 'loculi', 'city', '', NULL, NULL, 0, FALSE),
('Lodine', 'lodine', 'city', '', NULL, NULL, 0, FALSE),
('Lodè', 'lod', 'city', '', NULL, NULL, 0, FALSE),
('Loiri Porto San Paolo', 'loiri-porto-san-paolo', 'city', '', NULL, NULL, 0, FALSE),
('Lotzorai', 'lotzorai', 'city', '', NULL, NULL, 0, FALSE),
('Lula', 'lula', 'city', '', NULL, NULL, 0, FALSE),
('Lunamatrona', 'lunamatrona', 'city', '', NULL, NULL, 0, FALSE),
('Luogosanto', 'luogosanto', 'city', '', NULL, NULL, 0, FALSE),
('Luras', 'luras', 'city', '', NULL, NULL, 0, FALSE),
('Macomer', 'macomer', 'city', 'NU', 40.2644, 8.7753, 9993, FALSE),
('Magomadas', 'magomadas', 'city', '', NULL, NULL, 0, FALSE),
('Mamoiada', 'mamoiada', 'city', '', NULL, NULL, 0, FALSE),
('Mandas', 'mandas', 'city', '', NULL, NULL, 0, FALSE),
('Mara', 'mara', 'city', '', NULL, NULL, 0, FALSE),
('Maracalagonis', 'maracalagonis', 'city', '', NULL, NULL, 0, FALSE),
('Marrubiu', 'marrubiu', 'city', '', NULL, NULL, 0, FALSE),
('Martis', 'martis', 'city', '', NULL, NULL, 0, FALSE),
('Masainas', 'masainas', 'city', '', NULL, NULL, 0, FALSE),
('Masullas', 'masullas', 'city', '', NULL, NULL, 0, FALSE),
('Meana Sardo', 'meana-sardo', 'city', '', NULL, NULL, 0, FALSE),
('Milis', 'milis', 'city', '', NULL, NULL, 0, FALSE),
('Modolo', 'modolo', 'city', '', NULL, NULL, 0, FALSE),
('Mogorella', 'mogorella', 'city', '', NULL, NULL, 0, FALSE),
('Mogoro', 'mogoro', 'city', '', NULL, NULL, 0, FALSE),
('Monastir', 'monastir', 'city', '', NULL, NULL, 0, FALSE),
('Monserrato', 'monserrato', 'city', 'CA', 39.2589, 9.1417, 19771, TRUE),
('Monteleone Rocca Doria', 'monteleone-rocca-doria', 'city', '', NULL, NULL, 0, FALSE),
('Monti', 'monti', 'city', '', NULL, NULL, 0, FALSE),
('Montresta', 'montresta', 'city', '', NULL, NULL, 0, FALSE),
('Mores', 'mores', 'city', '', NULL, NULL, 0, FALSE),
('Morgongiori', 'morgongiori', 'city', '', NULL, NULL, 0, FALSE),
('Muravera', 'muravera', 'city', '', NULL, NULL, 0, FALSE),
('Muros', 'muros', 'city', '', NULL, NULL, 0, FALSE),
('Musei', 'musei', 'city', '', NULL, NULL, 0, FALSE),
('Narbolia', 'narbolia', 'city', '', NULL, NULL, 0, FALSE),
('Narcao', 'narcao', 'city', '', NULL, NULL, 0, FALSE),
('Neoneli', 'neoneli', 'city', '', NULL, NULL, 0, FALSE),
('Noragugume', 'noragugume', 'city', '', NULL, NULL, 0, FALSE),
('Norbello', 'norbello', 'city', '', NULL, NULL, 0, FALSE),
('Nughedu San Nicolò', 'nughedu-san-nicol', 'city', '', NULL, NULL, 0, FALSE),
('Nughedu Santa Vittoria', 'nughedu-santa-vittoria', 'city', '', NULL, NULL, 0, FALSE),
('Nule', 'nule', 'city', '', NULL, NULL, 0, FALSE),
('Nulvi', 'nulvi', 'city', '', NULL, NULL, 0, FALSE),
('Nurachi', 'nurachi', 'city', '', NULL, NULL, 0, FALSE),
('Nuragus', 'nuragus', 'city', '', NULL, NULL, 0, FALSE),
('Nurallao', 'nurallao', 'city', '', NULL, NULL, 0, FALSE),
('Nuraminis', 'nuraminis', 'city', '', NULL, NULL, 0, FALSE),
('Nureci', 'nureci', 'city', '', NULL, NULL, 0, FALSE),
('Nurri', 'nurri', 'city', '', NULL, NULL, 0, FALSE),
('Nuxis', 'nuxis', 'city', '', NULL, NULL, 0, FALSE),
('Nùoro', 'n-oro', 'city', '', NULL, NULL, 0, FALSE),
('Olbia', 'olbia', 'city', 'SS', 40.9234, 9.4992, 60731, TRUE),
('Oliena', 'oliena', 'city', '', NULL, NULL, 0, FALSE),
('Ollastra', 'ollastra', 'city', '', NULL, NULL, 0, FALSE),
('Ollolai', 'ollolai', 'city', '', NULL, NULL, 0, FALSE),
('Olmedo', 'olmedo', 'city', '', NULL, NULL, 0, FALSE),
('Olzai', 'olzai', 'city', '', NULL, NULL, 0, FALSE),
('Onanì', 'onan', 'city', '', NULL, NULL, 0, FALSE),
('Onifai', 'onifai', 'city', '', NULL, NULL, 0, FALSE),
('Oniferi', 'oniferi', 'city', '', NULL, NULL, 0, FALSE),
('Orani', 'orani', 'city', '', NULL, NULL, 0, FALSE),
('Orgosolo', 'orgosolo', 'city', '', NULL, NULL, 0, FALSE),
('Oristano', 'oristano', 'city', 'OR', 39.9036, 8.5916, 31671, TRUE),
('Orosei', 'orosei', 'city', '', NULL, NULL, 0, FALSE),
('Orotelli', 'orotelli', 'city', '', NULL, NULL, 0, FALSE),
('Orroli', 'orroli', 'city', '', NULL, NULL, 0, FALSE),
('Ortacesus', 'ortacesus', 'city', '', NULL, NULL, 0, FALSE),
('Ortueri', 'ortueri', 'city', '', NULL, NULL, 0, FALSE),
('Orune', 'orune', 'city', '', NULL, NULL, 0, FALSE),
('Oschiri', 'oschiri', 'city', '', NULL, NULL, 0, FALSE),
('Osidda', 'osidda', 'city', '', NULL, NULL, 0, FALSE),
('Osilo', 'osilo', 'city', '', NULL, NULL, 0, FALSE),
('Osini', 'osini', 'city', '', NULL, NULL, 0, FALSE),
('Ossi', 'ossi', 'city', '', NULL, NULL, 0, FALSE),
('Ottana', 'ottana', 'city', '', NULL, NULL, 0, FALSE),
('Ovodda', 'ovodda', 'city', '', NULL, NULL, 0, FALSE),
('Ozieri', 'ozieri', 'city', 'SS', 40.5858, 9.0014, 10594, FALSE),
('Pabillonis', 'pabillonis', 'city', '', NULL, NULL, 0, FALSE),
('Padria', 'padria', 'city', '', NULL, NULL, 0, FALSE),
('Padru', 'padru', 'city', '', NULL, NULL, 0, FALSE),
('Palau', 'palau', 'city', '', NULL, NULL, 0, FALSE),
('Palmas Arborea', 'palmas-arborea', 'city', '', NULL, NULL, 0, FALSE),
('Pattada', 'pattada', 'city', '', NULL, NULL, 0, FALSE),
('Pau', 'pau', 'city', '', NULL, NULL, 0, FALSE),
('Pauli Arbarei', 'pauli-arbarei', 'city', '', NULL, NULL, 0, FALSE),
('Paulilatino', 'paulilatino', 'city', '', NULL, NULL, 0, FALSE),
('Perdasdefogu', 'perdasdefogu', 'city', '', NULL, NULL, 0, FALSE),
('Perdaxius', 'perdaxius', 'city', '', NULL, NULL, 0, FALSE),
('Perfugas', 'perfugas', 'city', '', NULL, NULL, 0, FALSE),
('Pimentel', 'pimentel', 'city', '', NULL, NULL, 0, FALSE),
('Piscinas', 'piscinas', 'city', '', NULL, NULL, 0, FALSE),
('Ploaghe', 'ploaghe', 'city', '', NULL, NULL, 0, FALSE),
('Pompu', 'pompu', 'city', '', NULL, NULL, 0, FALSE),
('Porto Torres', 'porto-torres', 'city', 'SS', 40.8347, 8.4022, 22392, TRUE),
('Portoscuso', 'portoscuso', 'city', '', NULL, NULL, 0, FALSE),
('Posada', 'posada', 'city', '', NULL, NULL, 0, FALSE),
('Pozzomaggiore', 'pozzomaggiore', 'city', '', NULL, NULL, 0, FALSE),
('Pula', 'pula', 'city', 'CA', 38.9908, 9.0014, 7361, TRUE),
('Putifigari', 'putifigari', 'city', '', NULL, NULL, 0, FALSE),
('Quartu Sant''Elena', 'quartu-sant-elena', 'city', 'CA', 39.2422, 9.1833, 70879, TRUE),
('Quartucciu', 'quartucciu', 'city', '', NULL, NULL, 0, FALSE),
('Riola Sardo', 'riola-sardo', 'city', '', NULL, NULL, 0, FALSE),
('Romana', 'romana', 'city', '', NULL, NULL, 0, FALSE),
('Ruinas', 'ruinas', 'city', '', NULL, NULL, 0, FALSE),
('Sadali', 'sadali', 'city', '', NULL, NULL, 0, FALSE),
('Sagama', 'sagama', 'city', '', NULL, NULL, 0, FALSE),
('Samassi', 'samassi', 'city', '', NULL, NULL, 0, FALSE),
('Samatzai', 'samatzai', 'city', '', NULL, NULL, 0, FALSE),
('Samugheo', 'samugheo', 'city', '', NULL, NULL, 0, FALSE),
('San Basilio', 'san-basilio', 'city', '', NULL, NULL, 0, FALSE),
('San Gavino Monreale', 'san-gavino-monreale', 'city', '', NULL, NULL, 0, FALSE),
('San Giovanni Suergiu', 'san-giovanni-suergiu', 'city', '', NULL, NULL, 0, FALSE),
('San Nicolò Gerrei', 'san-nicol-gerrei', 'city', '', NULL, NULL, 0, FALSE),
('San Nicolò d''Arcidano', 'san-nicol-d-arcidano', 'city', '', NULL, NULL, 0, FALSE),
('San Sperate', 'san-sperate', 'city', '', NULL, NULL, 0, FALSE),
('San Teodoro', 'san-teodoro', 'city', 'SS', 40.7686, 9.6731, 5012, TRUE),
('San Vero Milis', 'san-vero-milis', 'city', '', NULL, NULL, 0, FALSE),
('San Vito', 'san-vito', 'city', '', NULL, NULL, 0, FALSE),
('Sanluri', 'sanluri', 'city', '', NULL, NULL, 0, FALSE),
('Sant''Andrea Frius', 'sant-andrea-frius', 'city', '', NULL, NULL, 0, FALSE),
('Sant''Anna Arresi', 'sant-anna-arresi', 'city', '', NULL, NULL, 0, FALSE),
('Sant''Antioco', 'sant-antioco', 'city', '', NULL, NULL, 0, FALSE),
('Sant''Antonio di Gallura', 'sant-antonio-di-gallura', 'city', '', NULL, NULL, 0, FALSE),
('Santa Giusta', 'santa-giusta', 'city', '', NULL, NULL, 0, FALSE),
('Santa Maria Coghinas', 'santa-maria-coghinas', 'city', '', NULL, NULL, 0, FALSE),
('Santa Teresa Gallura', 'santa-teresa-gallura', 'city', '', NULL, NULL, 0, FALSE),
('Santadi', 'santadi', 'city', '', NULL, NULL, 0, FALSE),
('Santu Lussurgiu', 'santu-lussurgiu', 'city', '', NULL, NULL, 0, FALSE),
('Sardara', 'sardara', 'city', '', NULL, NULL, 0, FALSE),
('Sarroch', 'sarroch', 'city', '', NULL, NULL, 0, FALSE),
('Sarule', 'sarule', 'city', '', NULL, NULL, 0, FALSE),
('Sassari', 'sassari', 'city', 'SS', 40.7259, 8.5556, 127525, TRUE),
('Scano di Montiferro', 'scano-di-montiferro', 'city', '', NULL, NULL, 0, FALSE),
('Sedilo', 'sedilo', 'city', '', NULL, NULL, 0, FALSE),
('Sedini', 'sedini', 'city', '', NULL, NULL, 0, FALSE),
('Segariu', 'segariu', 'city', '', NULL, NULL, 0, FALSE),
('Selargius', 'selargius', 'city', 'CA', 39.2558, 9.1678, 28905, TRUE),
('Selegas', 'selegas', 'city', '', NULL, NULL, 0, FALSE),
('Semestene', 'semestene', 'city', '', NULL, NULL, 0, FALSE),
('Seneghe', 'seneghe', 'city', '', NULL, NULL, 0, FALSE),
('Senis', 'senis', 'city', '', NULL, NULL, 0, FALSE),
('Sennariolo', 'sennariolo', 'city', '', NULL, NULL, 0, FALSE),
('Sennori', 'sennori', 'city', '', NULL, NULL, 0, FALSE),
('Senorbì', 'senorb', 'city', '', NULL, NULL, 0, FALSE),
('Serdiana', 'serdiana', 'city', '', NULL, NULL, 0, FALSE),
('Serramanna', 'serramanna', 'city', '', NULL, NULL, 0, FALSE),
('Serrenti', 'serrenti', 'city', '', NULL, NULL, 0, FALSE),
('Serri', 'serri', 'city', '', NULL, NULL, 0, FALSE),
('Sestu', 'sestu', 'city', 'CA', 39.3, 9.0917, 20958, TRUE),
('Settimo San Pietro', 'settimo-san-pietro', 'city', '', NULL, NULL, 0, FALSE),
('Setzu', 'setzu', 'city', '', NULL, NULL, 0, FALSE),
('Seui', 'seui', 'city', '', NULL, NULL, 0, FALSE),
('Seulo', 'seulo', 'city', '', NULL, NULL, 0, FALSE),
('Siamaggiore', 'siamaggiore', 'city', '', NULL, NULL, 0, FALSE),
('Siamanna', 'siamanna', 'city', '', NULL, NULL, 0, FALSE),
('Siapiccia', 'siapiccia', 'city', '', NULL, NULL, 0, FALSE),
('Siddi', 'siddi', 'city', '', NULL, NULL, 0, FALSE),
('Silanus', 'silanus', 'city', '', NULL, NULL, 0, FALSE),
('Siligo', 'siligo', 'city', '', NULL, NULL, 0, FALSE),
('Siliqua', 'siliqua', 'city', '', NULL, NULL, 0, FALSE),
('Silius', 'silius', 'city', '', NULL, NULL, 0, FALSE),
('Simala', 'simala', 'city', '', NULL, NULL, 0, FALSE),
('Simaxis', 'simaxis', 'city', '', NULL, NULL, 0, FALSE),
('Sindia', 'sindia', 'city', '', NULL, NULL, 0, FALSE),
('Sini', 'sini', 'city', '', NULL, NULL, 0, FALSE),
('Siniscola', 'siniscola', 'city', 'NU', 40.5719, 9.6944, 11466, FALSE),
('Sinnai', 'sinnai', 'city', 'CA', 39.3025, 9.2031, 17618, TRUE),
('Siris', 'siris', 'city', '', NULL, NULL, 0, FALSE),
('Siurgus Donigala', 'siurgus-donigala', 'city', '', NULL, NULL, 0, FALSE),
('Soddì', 'sodd', 'city', '', NULL, NULL, 0, FALSE),
('Solarussa', 'solarussa', 'city', '', NULL, NULL, 0, FALSE),
('Soleminis', 'soleminis', 'city', '', NULL, NULL, 0, FALSE),
('Sorgono', 'sorgono', 'city', '', NULL, NULL, 0, FALSE),
('Sorradile', 'sorradile', 'city', '', NULL, NULL, 0, FALSE),
('Sorso', 'sorso', 'city', '', NULL, NULL, 0, FALSE),
('Stintino', 'stintino', 'city', '', NULL, NULL, 0, FALSE),
('Suelli', 'suelli', 'city', '', NULL, NULL, 0, FALSE),
('Suni', 'suni', 'city', '', NULL, NULL, 0, FALSE),
('Tadasuni', 'tadasuni', 'city', '', NULL, NULL, 0, FALSE),
('Talana', 'talana', 'city', '', NULL, NULL, 0, FALSE),
('Telti', 'telti', 'city', '', NULL, NULL, 0, FALSE),
('Tempio Pausania', 'tempio-pausania', 'city', 'SS', 40.6814, 9.1081, 14052, FALSE),
('Tergu', 'tergu', 'city', '', NULL, NULL, 0, FALSE),
('Terralba', 'terralba', 'city', '', NULL, NULL, 0, FALSE),
('Tertenia', 'tertenia', 'city', '', NULL, NULL, 0, FALSE),
('Teti', 'teti', 'city', '', NULL, NULL, 0, FALSE),
('Teulada', 'teulada', 'city', '', NULL, NULL, 0, FALSE),
('Thiesi', 'thiesi', 'city', '', NULL, NULL, 0, FALSE),
('Tiana', 'tiana', 'city', '', NULL, NULL, 0, FALSE),
('Tinnura', 'tinnura', 'city', '', NULL, NULL, 0, FALSE),
('Tissi', 'tissi', 'city', '', NULL, NULL, 0, FALSE),
('Tonara', 'tonara', 'city', '', NULL, NULL, 0, FALSE),
('Torpè', 'torp', 'city', '', NULL, NULL, 0, FALSE),
('Torralba', 'torralba', 'city', '', NULL, NULL, 0, FALSE),
('Tortolì', 'tortol', 'city', 'NU', 39.9267, 9.6572, 11059, TRUE),
('Tramatza', 'tramatza', 'city', '', NULL, NULL, 0, FALSE),
('Tratalias', 'tratalias', 'city', '', NULL, NULL, 0, FALSE),
('Tresnuraghes', 'tresnuraghes', 'city', '', NULL, NULL, 0, FALSE),
('Triei', 'triei', 'city', '', NULL, NULL, 0, FALSE),
('Trinità d''Agultu e Vignola', 'trinit-d-agultu-e-vignola', 'city', '', NULL, NULL, 0, FALSE),
('Tuili', 'tuili', 'city', '', NULL, NULL, 0, FALSE),
('Tula', 'tula', 'city', '', NULL, NULL, 0, FALSE),
('Turri', 'turri', 'city', '', NULL, NULL, 0, FALSE),
('Ula Tirso', 'ula-tirso', 'city', '', NULL, NULL, 0, FALSE),
('Ulassai', 'ulassai', 'city', '', NULL, NULL, 0, FALSE),
('Uras', 'uras', 'city', '', NULL, NULL, 0, FALSE),
('Uri', 'uri', 'city', '', NULL, NULL, 0, FALSE),
('Urzulei', 'urzulei', 'city', '', NULL, NULL, 0, FALSE),
('Usellus', 'usellus', 'city', '', NULL, NULL, 0, FALSE),
('Usini', 'usini', 'city', '', NULL, NULL, 0, FALSE),
('Ussana', 'ussana', 'city', '', NULL, NULL, 0, FALSE),
('Ussaramanna', 'ussaramanna', 'city', '', NULL, NULL, 0, FALSE),
('Ussassai', 'ussassai', 'city', '', NULL, NULL, 0, FALSE),
('Uta', 'uta', 'city', '', NULL, NULL, 0, FALSE),
('Valledoria', 'valledoria', 'city', '', NULL, NULL, 0, FALSE),
('Vallermosa', 'vallermosa', 'city', '', NULL, NULL, 0, FALSE),
('Viddalba', 'viddalba', 'city', '', NULL, NULL, 0, FALSE),
('Villa San Pietro', 'villa-san-pietro', 'city', '', NULL, NULL, 0, FALSE),
('Villa Sant''Antonio', 'villa-sant-antonio', 'city', '', NULL, NULL, 0, FALSE),
('Villa Verde', 'villa-verde', 'city', '', NULL, NULL, 0, FALSE),
('Villacidro', 'villacidro', 'city', 'SU', 39.4586, 8.7369, 13958, FALSE),
('Villagrande Strisaili', 'villagrande-strisaili', 'city', '', NULL, NULL, 0, FALSE),
('Villamar', 'villamar', 'city', '', NULL, NULL, 0, FALSE),
('Villamassargia', 'villamassargia', 'city', '', NULL, NULL, 0, FALSE),
('Villanova Monteleone', 'villanova-monteleone', 'city', '', NULL, NULL, 0, FALSE),
('Villanova Truschedu', 'villanova-truschedu', 'city', '', NULL, NULL, 0, FALSE),
('Villanova Tulo', 'villanova-tulo', 'city', '', NULL, NULL, 0, FALSE),
('Villanovaforru', 'villanovaforru', 'city', '', NULL, NULL, 0, FALSE),
('Villanovafranca', 'villanovafranca', 'city', '', NULL, NULL, 0, FALSE),
('Villaperuccio', 'villaperuccio', 'city', '', NULL, NULL, 0, FALSE),
('Villaputzu', 'villaputzu', 'city', '', NULL, NULL, 0, FALSE),
('Villasalto', 'villasalto', 'city', '', NULL, NULL, 0, FALSE),
('Villasimius', 'villasimius', 'city', 'SU', 39.1431, 9.5222, 3711, TRUE),
('Villasor', 'villasor', 'city', '', NULL, NULL, 0, FALSE),
('Villaspeciosa', 'villaspeciosa', 'city', '', NULL, NULL, 0, FALSE),
('Villaurbana', 'villaurbana', 'city', '', NULL, NULL, 0, FALSE),
('Zeddiani', 'zeddiani', 'city', '', NULL, NULL, 0, FALSE),
('Zerfaliu', 'zerfaliu', 'city', '', NULL, NULL, 0, FALSE),
('Aeroporto di Cagliari Elmas', 'aeroporto-cagliari-elmas', 'airport', '', 39.2519, 9.0664, 0, TRUE),
('Aeroporto di Olbia Costa Smeralda', 'aeroporto-olbia-costa-smeralda', 'airport', '', 40.8987, 9.5176, 0, TRUE),
('Aeroporto di Alghero Fertilia', 'aeroporto-alghero-fertilia', 'airport', '', 40.6321, 8.2907, 0, TRUE),
('Porto di Cagliari', 'porto-cagliari', 'port', '', 39.2139, 9.1064, 0, TRUE),
('Porto di Olbia', 'porto-olbia', 'port', '', 40.9242, 9.5161, 0, TRUE),
('Porto di Porto Torres', 'porto-porto-torres', 'port', '', 40.8406, 8.4006, 0, TRUE),
('Porto di Golfo Aranci', 'porto-golfo-aranci', 'port', '', 41.0014, 9.6231, 0, TRUE),
('Porto di Arbatax', 'porto-arbatax', 'port', '', 39.9361, 9.7042, 0, FALSE),
('UniCa - Cagliari Centro', 'unica-cagliari-centro', 'university', '', 39.2161, 9.1122, 0, TRUE),
('UniCa - Monserrato Campus', 'unica-monserrato-campus', 'university', '', 39.2681, 9.1417, 0, TRUE),
('UniSS - Sassari Centro', 'uniss-sassari-centro', 'university', '', 40.7244, 8.5581, 0, TRUE);